/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.starlabs.vista.utilidades;

import cl.starlabs.controladores.CiudadJpaController;
import cl.starlabs.controladores.PropiedadJpaController;
import cl.starlabs.modelo.Ciudad;
import cl.starlabs.modelo.Cliente;
import cl.starlabs.modelo.Empleado;
import cl.starlabs.modelo.Propiedad;
import cl.starlabs.vista.calendario.NuevoEvento;
import java.awt.GraphicsConfiguration;
import java.awt.event.MouseEvent;
import java.math.BigInteger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.UIManager;

/**
 *
 * @author Victor Manuel Araya
 */
public class UtilidadBuscarPropiedad extends javax.swing.JFrame {

    EntityManagerFactory emf = null;
    Cliente cli = null;
    Propiedad pro = null;
    Empleado emp = null;
    
    public UtilidadBuscarPropiedad() {
        initComponents();
        emf = Persistence.createEntityManagerFactory("PU");
        this.setLocationRelativeTo(null);
        //rellenando combobox
        for(Ciudad c : new CiudadJpaController(emf).listar())
        {
            cmbCiudad.addItem(c.getNombre());
        }
    }

    public UtilidadBuscarPropiedad(Cliente cli, Propiedad pro ,Empleado emp) {
        initComponents();
        emf = Persistence.createEntityManagerFactory("PU");
        this.cli = cli;
        this.pro = pro;
        this.emp = emp;
        this.setLocationRelativeTo(null);
        
        //rellenando combobox
        for(Ciudad c : new CiudadJpaController(emf).listar())
        {
            cmbCiudad.addItem(c.getNombre());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbCiudad = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbPropiedad = new javax.swing.JComboBox();
        btnSeleccionar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StarLabs DreamHome :: Búsqueda de Propiedades");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Parámetros de Búsqueda"));

        jLabel1.setText("Ciudad");

        cmbCiudad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione..." }));
        cmbCiudad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCiudadItemStateChanged(evt);
            }
        });
        cmbCiudad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbCiudadFocusGained(evt);
            }
        });
        cmbCiudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbCiudadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbCiudadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbCiudadMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmbCiudadMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmbCiudadMouseReleased(evt);
            }
        });

        jLabel3.setText("Propiedad");

        cmbPropiedad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione..." }));
        cmbPropiedad.setEnabled(false);
        cmbPropiedad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPropiedadItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmbCiudad, 0, 267, Short.MAX_VALUE)
                    .addComponent(cmbPropiedad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/starlabs/iconos/book_next.png"))); // NOI18N
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.setEnabled(false);
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnSeleccionar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCiudadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbCiudadMousePressed

    }//GEN-LAST:event_cmbCiudadMousePressed

    private void cmbCiudadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbCiudadMouseEntered

    }//GEN-LAST:event_cmbCiudadMouseEntered

    private void cmbCiudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbCiudadMouseClicked

    }//GEN-LAST:event_cmbCiudadMouseClicked

    private void cmbCiudadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbCiudadFocusGained

    }//GEN-LAST:event_cmbCiudadFocusGained

    private void cmbCiudadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbCiudadMouseExited

    }//GEN-LAST:event_cmbCiudadMouseExited

    private void cmbCiudadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbCiudadMouseReleased

    }//GEN-LAST:event_cmbCiudadMouseReleased

    private void cmbCiudadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCiudadItemStateChanged
        if(cmbCiudad.getSelectedItem().toString().compareToIgnoreCase("Seleccione...") != 0) {
            //Obteniendo informacion de la ciudad seleccionada
            Ciudad ci = new CiudadJpaController(emf).buscarPorNombre(cmbCiudad.getSelectedItem().toString());
            //rellenando propiedades de la ciudad
            cmbPropiedad.setEnabled(true);
            for(Propiedad p : new PropiedadJpaController(emf).listarPorCiudad(ci.getIdciudad().toBigInteger())) {
                for(int i=0; i<cmbPropiedad.getItemCount(); i++) {
                    if(cmbPropiedad.getItemAt(i).toString().compareToIgnoreCase(p.getNumpropiedad()+": "+p.getCalle()) != 0) {
                        cmbPropiedad.addItem(p.getNumpropiedad()+": "+p.getCalle());
                    }
                }
            }
        }else{
            cmbPropiedad.setEnabled(false);
        }
    }//GEN-LAST:event_cmbCiudadItemStateChanged

    private void cmbPropiedadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPropiedadItemStateChanged
        if(cmbPropiedad.getSelectedItem().toString().compareToIgnoreCase("Seleccione...") != 0) {
            btnSeleccionar.setEnabled(true);
            pro = new PropiedadJpaController(emf).buscarPropiedadPorNumero(new BigInteger(cmbPropiedad.getSelectedItem().toString().split(":")[0]));
        }else{
            btnSeleccionar.setEnabled(false);
            pro = null;
        }
    }//GEN-LAST:event_cmbPropiedadItemStateChanged

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        NuevoEvento ne = new NuevoEvento(cli, pro, emp);
        this.dispose();
        ne.setVisible(true);
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        NuevoEvento ne = new NuevoEvento(cli, pro, emp);
        this.dispose();
        ne.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UtilidadBuscarPropiedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UtilidadBuscarPropiedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UtilidadBuscarPropiedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UtilidadBuscarPropiedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UtilidadBuscarPropiedad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JComboBox cmbCiudad;
    private javax.swing.JComboBox cmbPropiedad;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
