/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.starlabs.vista.bienvenida;
import cl.starlabs.modelo.Empleado;
import cl.starlabs.vista.calendario.Calendario;
import cl.starlabs.vista.calendario.NuevoEvento;
import cl.starlabs.vista.clientes.AgregarCliente;
import cl.starlabs.vista.clientes.ListarClientes;
import cl.starlabs.vista.empleados.AgregarEmpleado;
import cl.starlabs.vista.empleados.ListarEmpleados;
import cl.starlabs.vista.login.Login;
import cl.starlabs.vista.propiedades.ListarPropiedades;
import cl.starlabs.vista.propiedades.RegistrarPropiedad;
import cl.starlabs.vista.reportes.BuscarPropiedad;
import cl.starlabs.vista.utilidades.UtilidadBuscarPropietario;
import java.awt.Toolkit;
/**
 *
 * @author cetecom
 */
public class Bienvenida extends javax.swing.JFrame {

    /**
     * Creates new form Bienvenida
     */
    Empleado e = null;
    
    public Bienvenida(Empleado e) {
        initComponents();
        this.e = e;
        //this.setLocationRelativeTo(null);
        //this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        this.setTitle("StarLabs DreamHome | Conectado como: "+e.getNombre().toLowerCase()+" "+e.getApaterno().toLowerCase()+" "+e.getAmaterno().toLowerCase());
        menuSesion.setText("Sesión de "+e.getNombre().toLowerCase());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSesion = new javax.swing.JMenu();
        sesionLogout = new javax.swing.JMenuItem();
        sesionExit = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenu();
        clienteAgregar = new javax.swing.JMenuItem();
        clientesListar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        EmpleadoAgregar = new javax.swing.JMenuItem();
        menuEmpleadosListar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        agendaCalendario = new javax.swing.JMenuItem();
        agendaNuevoEvento = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuBuscarPorPropietario = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        ListarPropiedades = new javax.swing.JMenuItem();
        reporteReportepropiedades = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/starlabs/imagenes/wallpaper.png"))); // NOI18N

        menuSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/starlabs/iconos/user.png"))); // NOI18N
        menuSesion.setText("Sesión de");

        sesionLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        sesionLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/starlabs/iconos/action_stop.gif"))); // NOI18N
        sesionLogout.setText("Cerrar Sesión");
        sesionLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sesionLogoutActionPerformed(evt);
            }
        });
        menuSesion.add(sesionLogout);

        sesionExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        sesionExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/starlabs/iconos/door_out.png"))); // NOI18N
        sesionExit.setText("Salir de DreamHome");
        sesionExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sesionExitActionPerformed(evt);
            }
        });
        menuSesion.add(sesionExit);

        jMenuBar1.add(menuSesion);

        menuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/starlabs/iconos/vcard.png"))); // NOI18N
        menuCliente.setText("Clientes");

        clienteAgregar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        clienteAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/starlabs/iconos/vcard_add.png"))); // NOI18N
        clienteAgregar.setText("Agregar Nuevo");
        clienteAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteAgregarActionPerformed(evt);
            }
        });
        menuCliente.add(clienteAgregar);

        clientesListar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK));
        clientesListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/starlabs/iconos/vcard.png"))); // NOI18N
        clientesListar.setText("Lista de Clientes");
        clientesListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesListarActionPerformed(evt);
            }
        });
        menuCliente.add(clientesListar);

        jMenuBar1.add(menuCliente);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/starlabs/iconos/group.png"))); // NOI18N
        jMenu3.setText("Empleados");

        EmpleadoAgregar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_MASK));
        EmpleadoAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/starlabs/iconos/user_add.png"))); // NOI18N
        EmpleadoAgregar.setText("Agregar Nuevo");
        EmpleadoAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadoAgregarActionPerformed(evt);
            }
        });
        jMenu3.add(EmpleadoAgregar);

        menuEmpleadosListar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_MASK));
        menuEmpleadosListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/starlabs/iconos/group_link.png"))); // NOI18N
        menuEmpleadosListar.setText("Lista de Empleados");
        menuEmpleadosListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpleadosListarActionPerformed(evt);
            }
        });
        jMenu3.add(menuEmpleadosListar);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/starlabs/iconos/calendar.gif"))); // NOI18N
        jMenu4.setText("Agenda");

        agendaCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/starlabs/iconos/calendar_view_day.png"))); // NOI18N
        agendaCalendario.setText("Calendario");
        agendaCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendaCalendarioActionPerformed(evt);
            }
        });
        jMenu4.add(agendaCalendario);

        agendaNuevoEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/starlabs/iconos/calendar_add.png"))); // NOI18N
        agendaNuevoEvento.setText("Nuevo Evento");
        agendaNuevoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendaNuevoEventoActionPerformed(evt);
            }
        });
        jMenu4.add(agendaNuevoEvento);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/starlabs/iconos/building.png"))); // NOI18N
        jMenu5.setText("Propiedades");

        menuBuscarPorPropietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/starlabs/iconos/find.png"))); // NOI18N
        menuBuscarPorPropietario.setText("Buscar por propietario");
        menuBuscarPorPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscarPorPropietarioActionPerformed(evt);
            }
        });
        jMenu5.add(menuBuscarPorPropietario);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/starlabs/iconos/house.png"))); // NOI18N
        jMenuItem1.setText("Registrar Nueva Propiedad");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        ListarPropiedades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/starlabs/iconos/building_go.png"))); // NOI18N
        ListarPropiedades.setText("Lista de Propiedades");
        ListarPropiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarPropiedadesActionPerformed(evt);
            }
        });
        jMenu5.add(ListarPropiedades);

        jMenuBar1.add(jMenu5);

        reporteReportepropiedades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/starlabs/iconos/book.png"))); // NOI18N
        reporteReportepropiedades.setText("Reportes");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/starlabs/iconos/building_key.png"))); // NOI18N
        jMenuItem2.setText("Reporte de Propiedades");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        reporteReportepropiedades.add(jMenuItem2);

        jMenuBar1.add(reporteReportepropiedades);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 179, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sesionLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sesionLogoutActionPerformed
        e = null;
        this.dispose();
        Login l = new Login();
        l.setVisible(true);
    }//GEN-LAST:event_sesionLogoutActionPerformed

    private void sesionExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sesionExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sesionExitActionPerformed

    private void clienteAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteAgregarActionPerformed
        AgregarCliente ag = new AgregarCliente();
        ag.setVisible(true);
    }//GEN-LAST:event_clienteAgregarActionPerformed

    private void clientesListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesListarActionPerformed
        ListarClientes lc = new ListarClientes();
        lc.setVisible(true);
    }//GEN-LAST:event_clientesListarActionPerformed

    private void EmpleadoAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadoAgregarActionPerformed
        AgregarEmpleado agemp = new AgregarEmpleado();
        agemp.setVisible(true);
        agemp.setAlwaysOnTop(true);
    }//GEN-LAST:event_EmpleadoAgregarActionPerformed

    private void menuEmpleadosListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpleadosListarActionPerformed
        ListarEmpleados lem = new ListarEmpleados();
        lem.setVisible(true);
    }//GEN-LAST:event_menuEmpleadosListarActionPerformed

    private void agendaNuevoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendaNuevoEventoActionPerformed
        NuevoEvento ne = new NuevoEvento();
        ne.setVisible(true);
    }//GEN-LAST:event_agendaNuevoEventoActionPerformed

    private void agendaCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendaCalendarioActionPerformed
        Calendario cal = new Calendario();
        cal.setVisible(true);
    }//GEN-LAST:event_agendaCalendarioActionPerformed

    private void menuBuscarPorPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarPorPropietarioActionPerformed
        UtilidadBuscarPropietario ubp = new UtilidadBuscarPropietario();
        ubp.setVisible(true);
    }//GEN-LAST:event_menuBuscarPorPropietarioActionPerformed

    private void ListarPropiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarPropiedadesActionPerformed
        ListarPropiedades lpp = new ListarPropiedades();
        lpp.setVisible(true);
    }//GEN-LAST:event_ListarPropiedadesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        RegistrarPropiedad rpp = new RegistrarPropiedad(e);
        rpp.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        BuscarPropiedad rbp = new BuscarPropiedad();
        rbp.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenida().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EmpleadoAgregar;
    private javax.swing.JMenuItem ListarPropiedades;
    private javax.swing.JMenuItem agendaCalendario;
    private javax.swing.JMenuItem agendaNuevoEvento;
    private javax.swing.JMenuItem clienteAgregar;
    private javax.swing.JMenuItem clientesListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem menuBuscarPorPropietario;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenuItem menuEmpleadosListar;
    private javax.swing.JMenu menuSesion;
    private javax.swing.JMenu reporteReportepropiedades;
    private javax.swing.JMenuItem sesionExit;
    private javax.swing.JMenuItem sesionLogout;
    // End of variables declaration//GEN-END:variables
}
